services:
  ansible:
    build: .
    container_name: ansible
    image: ansible
    volumes:
      - /home/ccoupe/Projects/ansible:/ansible
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    working_dir: /ansible
    entrypoint: ["/bin/sh", "-c"]
    command: ["tail -f /dev/null"]
