---
- name: Install docker
  hosts: all
  become: true

  tasks:
    - name: Install docker dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - docker.io
          - docker-compose
          - docker-buildx
          - docker-clean
        update_cache: true

    - name: Add user to docker group
      user: name={{ ansible_user }}
            groups=docker
            append=yes
